librdmacm/preload.c: fix duplicate LFS symbols definitions
85f9747 introduces the preload of fcntl64 and it fails to build on armhf:

Assembler messages:
 Error: symbol `__fcntl_time64' is already defined
 Error: symbol `sendfile64' is already defined

On armhf (and potentially other 32 bits systems), glibc directs fcntl64
and fcntl to the same symbol name. preload.c defines both fcntl and fcntl64
and these 2 implementations are in fact tight to the same symbol, that causes
the double symbol error.

So only provide the definition of both fcntl and fcntl64 if they are 2
separate symbols.

This fixes the issue both for sendfile64 and fcntl64.

Fixes: 85f9747 ("librdmacm: Add support for fcntl64")
Signed-off-by: Hector Cao <hector.cao@canonical.com>